name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install Frontend Dependencies
      run: |
        cd chatbot-frontend
        npm ci
    
    - name: Build Frontend
      run: |
        cd chatbot-frontend
        npm run build
    
    - name: Test Frontend
      run: |
        cd chatbot-frontend
        npm test
    
    - name: Install Backend Dependencies
      run: |
        cd chatbot-backend
        npm ci
    
    - name: Test Backend
      run: |
        cd chatbot-backend
        npm test
    
  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-central-1

    - name: Deploy Frontend to S3
      run: |
        cd chatbot-frontend
        npm ci
        npm run build
        aws s3 sync build/ s3://your-s3-bucket-name --delete

    - name: Deploy Backend to ECS
      run: |
        cd chatbot-backend
        docker build -t your-ecr-repo:${{ github.sha }} .
        docker push your-ecr-repo:${{ github.sha }}
        aws ecs update-service --cluster your-cluster-name --service your-service-name --force-new-deployment

    - name: Deploy to Azure
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      run: |
        az login --service-principal -u ${{ fromJson(secrets.AZURE_CREDENTIALS).clientId }} -p ${{ fromJson(secrets.AZURE_CREDENTIALS).clientSecret }} --tenant ${{ fromJson(secrets.AZURE_CREDENTIALS).tenantId }}
        az cognitiveservices account update --name chatbot-text-analytics --resource-group chatbot-resources --sku S0